main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

upload/urls.py
from django.conf.urls import url
from .views import index, main_list, like
from django.contrib.auth.decorators import login_required
#from .views import ImgDeleteView

app_name = 'upload'
urlpatterns = [
#    url(r'^$', views.form, name='index'),
    url(r'^top/$', main_list.ImgIndexView.as_view(), name='main_list'),
    url(r'^mypage/$', login_required(index.ImgMyListView.as_view()), name='mypage'),
    url(r'^upload/create/$', index.ImgCreateUserView.as_view(), name='create'),
    url(r'^upload/update/(?P<pk>[0-9]+)/$',
        index.ImgUpdateView.as_view(), name='update'),
    url(r'^upload/delete/(?P<pk>[0-9]+)/$',
        index.ImgDeleteView.as_view(), name='delete'),
    url(r'^upload/like/(?P<id>[0-9]+)/$', like.like, name='like'),
#    url(r'^event01/$', index.ImgEvent01View.as_view(), name='event01'),
    url(r'^detail/(?P<pk>[0-9]+)/$', index.ImgDetailWithCommentView.as_view(), name='detail'),

#    url(r'^situation/$', index.SituationCreate.as_view(), name='situation'),
]

upload/models/buisiness_scene.py
from django.db import models


class BuisinessScene(models.Model):
    buisiness_scene = models.CharField(max_length=255)

    def __str__(self):
        return self.buisiness_scene

upload/models/color.py
from django.db import models


class Color(models.Model):
    color = models.CharField(max_length=255, unique=True)
    def __str__(self):
        return self.color

upload/models/favorite.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


class Favorite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)

    content_type = models.ForeignKey(ContentType,
                                    on_delete=models.CASCADE)

    object_id = models.PositiveIntegerField()

    content_object = GenericForeignKey('content_type', 'object_id')

    created = models.DateTimeField(auto_now_add=True)

upload/models/get_image_path.py
import os
import uuid

def get_image_path(self, filename):
    prefix = 'images/'
    name = str(uuid.uuid4()).replace('-', '')
    extension = os.path.splitext(filename)[-1]
    return prefix + name + extension

upload/models/img.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from upload.models import img, buisiness_scene, private_scene, color, season, theme
from upload.models.get_image_path import get_image_path

import os
import uuid
from PIL import Image



class Img(models.Model):
    file       = models.ImageField("ファイル", upload_to=get_image_path)

    buisiness_scene  = models.ManyToManyField(buisiness_scene.BuisinessScene, blank=True)
    private_scene  = models.ManyToManyField(private_scene.PrivateScene, blank=True)
    season     = models.ManyToManyField(season.Season, blank=True)
    color      = models.ManyToManyField(color.Color, blank=True)
    theme      = models.ManyToManyField(theme.Theme, blank=True)

    message    = models.CharField("ひとことコメント", max_length=255, blank=True)

    is_public  = models.BooleanField("未登録ユーザに公開", default=True)


    user       = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE,
                            blank=True, null=True)
    created_at = models.DateTimeField("作成日", auto_now_add=True)
    updated_at = models.DateTimeField("更新日", auto_now=True)

    favorited  = models.IntegerField("お気に入り登録数", default=0)

    rated = models.IntegerField("評価者数", default=0)
#    rate_sum = models.IntegerField("評価累計", default=0)
#    rate_ave = models.IntegerField("評価平均", default=0)

#    def __unicode__(self):
#        return self.title

    def get_filename(self):
        return os.path.basename(self.file.name)

upload/models/like.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)

    content_type = models.ForeignKey(ContentType,
                                    on_delete=models.CASCADE)

    object_id = models.PositiveIntegerField()

    content_object = GenericForeignKey('content_type', 'object_id')

    created = models.DateTimeField(auto_now_add=True)

upload/models/like_counter.py
from django.db import models
from upload.models.like import Like

upload/models/private_scene.py
from django.db import models


class PrivateScene(models.Model):
    private_scene = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.private_scene

upload/models/season.py
from django.db import models


class Season(models.Model):
    season = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.season

upload/models/theme.py
from django.db import models


class Theme(models.Model):
    theme  = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.theme

upload/views/favorite.py
from django.shortcuts import render, redirect
from upload.models import img, favorite
from django.http import JsonResponse


def favorite(request):
    if request.method == 'POST':
        user = request.user
        img_pk = request.POST.get('num')
        obj = img.Img.objects.get(pk=img_pk)

        if favorite.Favorite.objects.filter(user=user,content_object=obj).exists():
            
        else:
            favo = favorite.Favorite.objects.create(user=user,content_object=obj)
            favo.save()
            return JsonResponse()

upload/views/index.py
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.views.generic.edit import FormMixin
from upload.models import (
    img,
)
from upload.forms import (
    ImgForm,
)
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.db.models import Count

#from extra_views import CreateWithInlinesView, InlineFormSet


class ImgMyListView(generic.ListView):
    def get_queryset(self):
        return img.Img.objects.filter(user__exact=self.request.user).order_by('-created_at')
    paginate_by = 30


class ImgCreateUserView(generic.CreateView):
    model = img.Img
    form_class = ImgForm

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        return super(ImgCreateUserView, self).form_valid(form)

    success_url = reverse_lazy("upload:main_list")


class ImgUpdateView(generic.UpdateView):
    model = img.Img
    form_class = ImgForm
    success_url = reverse_lazy("upload:mypage")
 
 
class ImgDeleteView(generic.DeleteView):
    model = img.Img
    success_url = reverse_lazy("upload:mypage")




"""    def get_context_data(self, **kwargs):
        context = super(ImgDetailView, self).get_context_data(**kwargs)
        return context
"""


class ImgDetailWithCommentView(generic.DetailView):
    model = img.Img
    """
    form_class = CommentCreateForm
    def form_valid(self, form):
        img_pk = self.kwargs['pk']
        self.object = form.save(commit=False)
        self.object.target = img.Img.objects.get(pk=img_pk)
        self.object.save()
        return redirect('upload:detail', pk=img_pk)

    def img(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    """

class ImgVoteView(generic.UpdateView):
    model = img.Img
    form_class = ImgForm
    success_url = reverse_lazy("upload:mypage")

upload/views/index_created_desc.py
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.db.models import Count

from upload.models import (
    Img,
    Situation, ClothColor, CoordinateStyle, Season, Purpose,
    Comment,
)
from upload.forms import (
    ImgForm,
    SituationForm, ColorForm, StyleForm, SeasonForm, PurposeForm,
    CommentCreateForm,
)

class ImgIndexView(generic.ListView):
    def get_queryset(self):
        return Img.objects.order_by('-created_at')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['situation_list'] = Situation.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['color_list'] = ClothColor.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['style_list'] = CoordinateStyle.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['season_list'] = Season.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['purpose_list'] = Purpose.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        return context
    paginate_by = 30
    template_name = 'upload/index_created_desc.html'

upload/views/index_many.py
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.db.models import Count

from upload.models import (
    Img,
    Situation, ClothColor, CoordinateStyle, Season, Purpose,
    Comment,
)
from upload.forms import (
    ImgForm,
    SituationForm, ColorForm, StyleForm, SeasonForm, PurposeForm,
    CommentCreateForm,
)

class ImgIndexView(generic.ListView):
    def get_queryset(self):
        return Img.objects.order_by('created_at')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['situation_list'] = Situation.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['color_list'] = ClothColor.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['style_list'] = CoordinateStyle.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['season_list'] = Season.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['purpose_list'] = Purpose.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        return context
    paginate_by = 30
    template_name = 'upload/index_created_asc.html'

upload/views/index_popular.py
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.db.models import Count

from upload.models import (
    Img,
    Situation, ClothColor, CoordinateStyle, Season, Purpose,
    Comment,
)
from upload.forms import (
    ImgForm,
    SituationForm, ColorForm, StyleForm, SeasonForm, PurposeForm,
    CommentCreateForm,
)

class ImgIndexView(generic.ListView):
    def get_queryset(self):
        return Img.objects.order_by('created_at')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['situation_list'] = Situation.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['color_list'] = ClothColor.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['style_list'] = CoordinateStyle.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['season_list'] = Season.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['purpose_list'] = Purpose.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        return context
    paginate_by = 30
    template_name = 'upload/index_created_asc.html'

upload/views/like.py
from django.shortcuts import render, redirect
from upload.models.img import Img
from upload.models.like import Like
from django.http import JsonResponse
from django.http import HttpResponse
import json


def like(request,id):
    if request.method == 'POST':
        user = request.user
        obj  = Img.objects.get(id=id)
        like = Like.objects.create(user=user,content_object=obj)
        like.save()

        obj.favorited += 1
        obj.save()
        #data = request.POST.get('id')
        ok = "お気に入りに登録しました。"
        #response = json.dumps({'message':request.POST.get('id')})
        #return HttpResponse(response)

        d = {
            'message': ok
        }
        return JsonResponse(d)

"""
def like(request, id):
    user = request.user
    obj  = img.Img.objects.get(id=id)
    if request.method == 'POST':
        like = Like.objects.create(user=user,content_object=obj)
        like.save()
        return redirect('upload:main_list')
"""

upload/views/main_list.py
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.db.models import Count


from upload.models import (
    buisiness_scene, private_scene, color, season, theme,
)
from upload.models.img import Img
from upload.models.like import Like
from upload.models.rate import Rate
from upload.forms import (
    ImgForm,
)


from accounts.models import profile
from accounts.forms import (
    CustomUserCreationForm, SigninForm, ProfileForm
)




class ImgIndexView(generic.ListView):

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['buisiness_scene_list'] = buisiness_scene.BuisinessScene.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['private_scene_list'] = private_scene.PrivateScene.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['color_list'] = color.Color.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['season_list'] = season.Season.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]
        context['theme_list'] = theme.Theme.objects.annotate(
            img_num=Count('img')).order_by('-img_num')[:3]



        buisiness_scenes = buisiness_scene.BuisinessScene.objects.all()
        private_scenes = private_scene.PrivateScene.objects.all()
        seasons = season.Season.objects.all()
        colors = color.Color.objects.all()
        themes = theme.Theme.objects.all()

        context['buisiness_scenes'] = buisiness_scenes
        context['private_scenes'] = private_scenes
        context['seasons'] =seasons
        context['colors'] = colors
        context['themes'] = themes



        rate_img = Rate.objects.filter(user__exact=self.request.user,
                                       objent_id__exact=img.id)

        return context

    def get_queryset(self):
        # デフォルトは全件
        results = Img.objects.order_by('-favorited')

        # GETのURLクエリパラメータを取得する
        # 該当のクエリパラメータが存在しない場合は、[]が返ってくる
        q_buisiness_scenes = self.request.GET.getlist('buisiness_scene')
        q_private_scenes = self.request.GET.getlist('private_scene')
        q_seasons = self.request.GET.getlist('season')
        q_colors = self.request.GET.getlist('color')
        q_themes = self.request.GET.getlist('theme')

        if len(q_buisiness_scenes) != 0:
            buisiness_scenes = [x for x in q_buisiness_scenes]
            results = results.filter(buisiness_scene__in=buisiness_scenes)
        if len(q_private_scenes) != 0:
            private_scenes = [x for x in q_private_scenes]
            results = results.filter(private_scene__in=private_scenes)
        if len(q_seasons) != 0:
            seasons = [x for x in q_seasons]
            results = results.filter(season__in=seasons)
        if len(q_colors) != 0:
            colors = [x for x in q_colors]
            results = results.filter(color__in=colors)
        if len(q_themes) != 0:
            themes = [x for x in q_themes]
            results = results.filter(theme__in=themes)

        return results

    paginate_by = 30
    template_name = 'upload/main_list.html'


"""
def for_ajax(req):    # AJAXに答える関数
    import json
    from django.http import HttpResponse,Http404

    if req.method == 'POST':
        txt = req.POST['your_txt']  # POSTデータを取得して
        surprise_txt = txt + "!!!"  # 加工
        
        response = json.dumps({'':,})  # JSON形式に直して・・

        return HttpResponse(response,mimetype="text/javascript")  # 返す。JSONはjavascript扱いなのか・・

    else:
        raise Http404  # GETリクエストを404扱いにしているが、実際は別にしなくてもいいかも
"""

upload/views/search.py
from django.shortcuts import render, redirect
from upload.models import img
from upload.models.like import Like
from django.http import JsonResponse

templates/upload/filterselect.html
<div class="row hidden-xs">
  <div class="col-sm-12">
    <h3>Situation</h3>
    {% for situation in situation_list %}
    <p>{{ situation }}</p>
    {% endfor %}
  </div>
  <div class="col-sm-12">
    <h3>Color</h3>
    {% for color in color_list %}
    <p>{{ color }}</p>
    {% endfor %}
  </div>
  <div class="col-sm-12">
    <h3>Style</h3>
    {% for style in style_list %}
    <p>{{ style }}</p>
    {% endfor %}
  </div>
  <div class="col-sm-12">
    <h3>Season</h3>
    {% for season in season_list %}
    <p>{{ season }}</p>
    {% endfor %}
  </div>
  <div class="col-sm-12">
    <h3>Purpose</h3>
    {% for purpose in purpose_list %}
    <p>{{ purpose }}</p>
    {% endfor %}
  </div>
</div>


<!--   smartphone view   -->
<div class="row hidden-sm hidden-md hidden-lg container">
<!--  <form method="post" action="{ url 'upload:sort' %}" id="sortselect">-->
  <form method="POST" action="" name="filter_form">
    {% csrf_token %}
    <select id="sort" name="sort">
      <option value="1">新着順</option>
      <option value="2">古い順</option>
      <option value="3">評価の高い順</option>
      <option value="4">評価数の多い順</option>
    </select>
      <a data-toggle="collapse" href="#filter-collapse">
         詳細条件
      </a>
        <div id="filter-collapse" class="collapse">
            <div class="form-group row">
              <label class="control-form-label col-xs-12">
              Situation
              </label>
              <div class="container">
              {% for situation in situation_list %}
                <label class="custom-control custom-checkbox checkbox-inline">
                  <input name="situation" type="checkbox" class="custom-control-input">
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description">{{ situation }} ({{ situation.img_num }})</span>
                </label>
              {% endfor %}
              </div>
            </div><hr>

            <div class="form-group row">
              <label class="control-form-label col-xs-12">
              Color
              </label>
              <div class="container">
              {% for color in color_list %}
                <label class="custom-control custom-checkbox checkbox-inline">
                  <input name="situation" type="checkbox" class="custom-control-input">
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description">{{ color }} ({{ color.img_num }})</span>
                </label>
              {% endfor %}
              </div>
            </div><hr>

            <div class="form-group row">
              <label class="control-form-label col-xs-12">
              Style
              </label>
              <div class="container">
              {% for style in style_list %}
                <label class="custom-control custom-checkbox checkbox-inline">
                  <input name="situation" type="checkbox" class="custom-control-input">
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description">{{ style }} ({{ style.img_num }})</span>
                </label>
              {% endfor %}
              </div>
            </div><hr>

            <div class="form-group row">
              <label class="control-form-label col-xs-12">
              Season
              </label>
              <div class="container">
              {% for season in season_list %}
                <label class="custom-control custom-checkbox checkbox-inline">
                  <input name="situation" type="checkbox" class="custom-control-input">
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description">{{ season }} ({{ season.img_num }})</span>
                </label>
              {% endfor %}
              </div>
            </div><hr>

            <div class="form-group row">
              <label class="control-form-label col-xs-12">
              Purpose
              </label>
              <div class="container">
              {% for purpose in purpose_list %}
                <label class="custom-control custom-checkbox checkbox-inline">
                  <input name="situation" type="checkbox" class="custom-control-input">
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description">{{ purpose }} ({{ purpose.img_num }})</span>
                </label>
              {% endfor %}
              </div>
            </div>
        </div>
    <input type="submit" value="表示"></input>
  </form>
</div>

templates/upload/img_form.html
{% extends "base.html" %}

{% block active-upload %}class="active"{% endblock active-upload %}

{% block content %}
    <form action="" method="POST" enctype='multipart/form-data'>

        <div class="form-group row">
<!--      { for file in form.file %}
          <label for="{ field.id_for_label }}" class="col-sm-2 col-form-label">
            { file.label }}
          </label>
          <div class="col-sm-10">
            { file }}
          </div>
      { endfor %}-->
<label for="{{ form.file.field.id_for_label }}" class="col-sm-2 col-form-label">
{{ form.file.label }}
</label>
<div class="col-sm-10">
{{ form.file }}
</div>
        </div>

        <div class="form-group row">
        <label class="control-form-label col-sm-2">
        {{ form.situation.label }}
        </label>
        <div>
      {% for situation in form.situation %}
        <label class="custom-control custom-checkbox checkbox-inline">
          <input name="situation" type="checkbox" class="custom-control-input">
          <span class="custom-control-indicator"></span>
          <span class="custom-control-description">{{ situation }}</span>
        </label>
      {% endfor %}
        </div>
        </div>

        <div class="form-group row">
        <label class="control-form-label col-sm-2">
        {{ form.color.label }}
        </label>
        <div id="{{ form.color.field.id }}">
      {% for color in form.color %}
        <label class="custom-control custom-checkbox checkbox-inline">
          <input name="situation" type="checkbox" class="custom-control-input">
          <span class="custom-control-indicator"></span>
          <span class="custom-control-description">{{ color }}</span>
        </label>
      {% endfor %}
        </div>
        </div>

        <div class="form-group row">
        <label class="control-form-label col-sm-2">
        {{ form.style.label }}
        </label>
        <div id="{{ form.style.field.id }}">
      {% for style in form.style %}
        <label class="custom-control custom-checkbox checkbox-inline">
          <input name="situation" type="checkbox" class="custom-control-input">
          <span class="custom-control-indicator"></span>
          <span class="custom-control-description">{{ style }}</span>
        </label>
      {% endfor %}
        </div>
        </div>

        <div class="form-group row">
        <label class="control-form-label col-sm-2">
        {{ form.season.label }}
        </label>
        <div id="{{ form.season.field.id }}">
      {% for season in form.season %}
        <label class="custom-control custom-checkbox checkbox-inline">
          <input name="situation" type="checkbox" class="custom-control-input">
          <span class="custom-control-indicator"></span>
          <span class="custom-control-description">{{ season }}</span>
        </label>
      {% endfor %}
        </div>
        </div>

        <div class="form-group row">
        <label class="control-form-label col-sm-2">
        {{ form.purpose.label }}
        </label>
        <div id="{{ form.purpose.field.id }}">
      {% for purpose in form.purpose %}
        <label class="custom-control custom-checkbox checkbox-inline">
          <input name="situation" type="checkbox" class="custom-control-input">
          <span class="custom-control-indicator"></span>
          <span class="custom-control-description">{{ purpose }}</span>
        </label>
      {% endfor %}
        </div>
        </div>


      {% csrf_token %}
      <div class="text-xs-center">
        <button type="submit" id="upload-btn" class="btn btn-default">投稿する</button>
        <a href="{% url 'upload:index' %}" class="btn btn-link">やめる</a>
      </div>
    </form>
<a href="{% url 'upload:situation' %}"><h2>SituationCreate</h2></a>

{% endblock content %}

templates/upload/index_created_asc.html
{% extends "base.html" %}
{% load staticfiles %}


{% block title %}Top{% endblock title %}


{% block extrahead %}
<link href="{% static 'css/img-size-fix.css' %}" rel="stylesheet">
{% endblock extrahead %}


{% block active-home %}class="active"{% endblock active-home %}


{% block sortmenulist %}
{% include "upload/filterselect.html" %}
{% endblock sortmenulist %}


{% block content %}
    <div id="main-content-imgs">
    {% for img in img_list %}
      <div class="img-item">
        <a href="{% url 'upload:detail' img.pk %}">
          <img src="{{ img.file.url }}" alt="{{ img.title }}">
        </a>
<!--          <a href="#">-->
<!--            <p>{ img.user }}</p>
          </a>-->
      </div>
    {% endfor %}
    </div>

    <div class="text-xs-center">
      {% include "upload/page.html" %}
    </div>
{% endblock content %}